name: Renovate
on:
  schedule:
    - cron: '0 0/4 * * *'
  issues:
    types: [opened, edited]
  workflow_dispatch: 

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.6
        with:
          renovate-version: full
          configurationFile: .github/renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
        
          